services:
  mysql:
    image: mysql:8.4
    container_name: moneytracker-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: money_tracker
      MYSQL_USER: moneytracker
      MYSQL_PASSWORD: moneytracker

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: